### ISSUE TITLE
Heavy memory consumption and container crash when trying to upload more than 3.0Go of files

### ISSUE THREAD

**Issue by prometek** [GREsau/localstack-persist#3]
Hi, first of all thanks for your work it is amazing.

When I try to upload more than 3.0Go of files in the bucket with your image, (I have exactly 4.5Go to upload) the memory goes heavy (It fills entirely my 16Gb RAM) which cause my computer to freeze and the docker container to crash. Do you have any idea how I can reduce the memory consumption ? 

Thanks

**Comment by prometek** [comment]
I do not use the `latest` tag.
Here is what I've put in my docker-compose:
```
localstack:
    image: gresau/localstack-persist
    environment:
      - PERSIST_DEFAULT
      - PERSIST_S3=1
    ports:
      - "4566:4566"
    volumes:
      - "./my-localstack-data:/persisted-data"
```

In case, I ran your command, here is the output: `2023-10-05T18:41:58.728280475Z`
